;------------------------------------------------------------------------------
; Filename: mfunc15.mac
; Description: Tool Unclamp Macro
; Notes: Uses MEM261, MEM266, or MEM964 to determine if user has an active input.
; Requires: CNC12 V4.66+
; Revision Date: 03 Apr 2025
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; PLC Variables:
; ToolUnclampedState_M        IS MEM12  (#70012)
; DrawBarReleasedDisable_M    IS MEM261 (#70261)
; ToolIsUnclampedDisable_M    IS MEM266 (#70266)
; DrawBarIsUpDisabled_M       IS MEM964 (#70964)
;------------------------------------------------------------------------------
IF #4201 || #4202 THEN GOTO 1000    ;Skip macro if graphing or searching

N100

M94 /15                             ;Turn on ToolUnclamp request
IF #70261 && #70266 && #70964 THEN GOTO 200 ;Determine if input is used.
M101 /70012                         ;Wait until tool is Unclamped.
GOTO 1000

N200
G4 P3                               ;Wait 3 seconds

N1000   ;End of Macro