;------------------------------------------------------------------------------
; Filename: mfunc40.mac
; Description: Oscillation Off
; Notes:
; Requires: CNC12 V5.08
; Revision Date: 01 AUG 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100                             ;Insert your code between N100 and N1000  

M95 /46                          ;End Oscillation Request

N1000                            ;End of Macro