;------------------------------------------------------------------------------
; Filename: mfunc11.mac
; Description: Turn Clamp Off Macro
; Notes:
; Requires: CNC12 AcornSix V5.00+ (Mill/Router)
; Revision Date: 3 Jun 2024
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                         ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000  ;Skip macro if graphing or searching

N100

M95 /10                           ;Rst Clamp On

N1000                             ;End of Macro

