;------------------------------------------------------------------------------
; Filename: mfunc60.mac - to run from aux 8, p195= 6011
; M60 macro PARK for mill and lathe
; Description: User Customizable Macro
; Notes:
; Please see TB300 for tips on writing custom macros.
;------------------------------------------------------------------------------

IF #50010                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching
IF #50010                        ;Prevent lookahead from parsing past here

IF #9413 == 0 THEN GOTO 100 ELSE GOTO 200

N100
G90
G53 L100 x0y0z0
GOTO 1000

N200

G65 "#400\system\park.mac"


GOTO 1000

N1000                            ;End of Macro