; Single Boundary Digitizing Pass X+
; ------------------------------------
; Assumes you are already at clearance height sitting over beginning of next segment

; INPUTS
; ------
; A: Step-along value
; B: Clearance Height
; C: Minimum Depth
; D: Distance to digitize

DEFINE <STEP_ALONG_VALUE> #a
DEFINE <DIRECTION> #b
DEFINE <MINIMUM_DEPTH> #c
DEFINE <DISTANCE_TO_DIGITIZE> #d

DEFINE <MESSAGE_TIME_IN_SECONDS>             #100
DEFINE <M115_Z_POSITION>                     #101
DEFINE <STARTING_X_POSITION>                 #102
DEFINE <X_POS_AFTER_STEPOVER>                #103
DEFINE <ORIGINAL_POSITIONING_MODE>           #104
DEFINE <X_POS_BEFORE_STEPOVER>               #105
DEFINE <SLOW_PROBE_RATE>                     #106
DEFINE <PROBE_PULLBACK_DIST>                 #107
DEFINE <FAST_PROBE_RATE>                     #108
DEFINE <Y_POS_BEFORE_STEPOVER>               #109
DEFINE <STARTING_Y_POSITION>                 #110
DEFINE <Y_POS_AFTER_STEPOVER>                #111
DEFINE <POSITIONING_MODE>                    #4003
DEFINE <CURRENT_POSITION_AXIS_1>             #5041
DEFINE <CURRENT_POSITION_AXIS_2>             #5042
DEFINE <CURRENT_POSITION_AXIS_3>             #5043
DEFINE <TOUCH_PROBE_PLC_INPUT_PARAMETER>     #9011
DEFINE <PROBING_RECOVERY_DISTANCE_PARAMETER> #9013
DEFINE <FAST_PROBING_RATE_PARAMETER>         #9014
DEFINE <SLOW_PROBING_RATE_PARAMETER>         #9015
DEFINE <PROBING_SEARCH_DISTANCE_PARAMETER>   #9016
DEFINE <PROBE_SETTINGS_PARAMETER>            #9155
DEFINE <DP7_PULLBACK_DISTANCE_PARAMETER>     #9392
DEFINE <DP7_PULLBACK_FEEDRATE_PARAMETER>     #9393
DEFINE <DP7_MEASURING_FEEDRATE_PARAMETER>    #9394
DEFINE <LAST_PROBE_TRIP>                     #25022
DEFINE <PROBE_PROTECTION_ENABLED>            #32001

DEFINE <PROBE_NOT_TRIPPED>        0
DEFINE <ENABLE_PROBE_PROTECTION>  0
DEFINE <PROBE_TRIPPED>            1
DEFINE <DISABLE_PROBE_PROTECTION> 1
DEFINE <DP7_PROBE>                2

DEFINE <ABSOLUTE_POSITIONING> G90
DEFINE <INCREMENTAL_POSITIONING> G91
DEFINE <IS_GREATER_THAN> GT
DEFINE <IS_GREATER_THAN_OR_EQUAL_TO> GE
DEFINE <IS_LESS_THAN_OR_EQUAL_TO> LE
DEFINE <IS_LESS_THAN> LT
DEFINE <DOES_NOT_EQUAL> NE

DEFINE <TOLERANCE> 0.0001

<SLOW_PROBE_RATE> = <DP7_MEASURING_FEEDRATE_PARAMETER>
IF <PROBE_SETTINGS_PARAMETER> <DOES_NOT_EQUAL> <DP7_PROBE> THEN <SLOW_PROBE_RATE> = <SLOW_PROBING_RATE_PARAMETER>

<FAST_PROBE_RATE> = <DP7_PULLBACK_FEEDRATE_PARAMETER>
IF <PROBE_SETTINGS_PARAMETER> <DOES_NOT_EQUAL> <DP7_PROBE> THEN <FAST_PROBE_RATE> = <FAST_PROBING_RATE_PARAMETER>

<PROBE_PULLBACK_DIST> = <DP7_PULLBACK_DISTANCE_PARAMETER>
IF <PROBE_SETTINGS_PARAMETER> <DOES_NOT_EQUAL> <DP7_PROBE> THEN <PROBE_PULLBACK_DIST> = <PROBING_RECOVERY_DISTANCE_PARAMETER>

IF <STEP_ALONG_VALUE> <IS_LESS_THAN> <PROBE_PULLBACK_DIST> THEN GOTO 666
N665
GOTO 667
N666
STEP-OVER IS EXCEEDED BY PROBE PULLBACK!
N667

<ORIGINAL_POSITIONING_MODE> = <POSITIONING_MODE>

<MESSAGE_TIME_IN_SECONDS> = 10

<STARTING_X_POSITION> = <CURRENT_POSITION_AXIS_1>
<STARTING_Y_POSITION> = <CURRENT_POSITION_AXIS_2>


; Begin 1) Down 2) Step-over cycle

N1
; 1) Down

<ABSOLUTE_POSITIONING>

; Probe Z to surface, going no lower than the minimum z depth or the probe 
; search distance. If the probe search distance would keep us above the minimum 
; depth, then use the probe search distance; otherwise, use the minimum depth.
IF [<CURRENT_POSITION_AXIS_3> - <PROBING_SEARCH_DISTANCE_PARAMETER>] <IS_GREATER_THAN> <MINIMUM_DEPTH> THEN <M115_Z_POSITION> = [<CURRENT_POSITION_AXIS_3> - <PROBING_SEARCH_DISTANCE_PARAMETER>] ELSE <M115_Z_POSITION> = <MINIMUM_DEPTH>
M115 /Z<M115_Z_POSITION> P<TOUCH_PROBE_PLC_INPUT_PARAMETER> F<SLOW_PROBE_RATE>
M122

; Pull back off of the surface by the probe retract distance
<INCREMENTAL_POSITIONING> G01 F<FAST_PROBE_RATE>
<PROBE_PROTECTION_ENABLED> = <DISABLE_PROBE_PROTECTION>
IF <PROBE_SETTINGS_PARAMETER> <DOES_NOT_EQUAL> <DP7_PROBE> THEN Z<PROBE_PULLBACK_DIST>
<PROBE_PROTECTION_ENABLED> = <ENABLE_PROBE_PROTECTION>



; Break out if we have gotten the last point
IF <DIRECTION> EQ 0 THEN GOTO 1000
IF <DIRECTION> EQ 1 THEN GOTO 2000
IF <DIRECTION> EQ 2 THEN GOTO 3000
IF <DIRECTION> EQ 3 THEN GOTO 4000
N1000
IF <CURRENT_POSITION_AXIS_1> <IS_LESS_THAN_OR_EQUAL_TO> [<STARTING_X_POSITION> - <DISTANCE_TO_DIGITIZE> + <TOLERANCE>] THEN GOTO 9999
GOTO 5000
N2000
IF <CURRENT_POSITION_AXIS_1> <IS_GREATER_THAN_OR_EQUAL_TO> [<STARTING_X_POSITION> + <DISTANCE_TO_DIGITIZE> - <TOLERANCE>] THEN GOTO 9999
GOTO 5000
N3000
IF <CURRENT_POSITION_AXIS_2> <IS_LESS_THAN_OR_EQUAL_TO> [<STARTING_Y_POSITION> - <DISTANCE_TO_DIGITIZE> + <TOLERANCE>] THEN GOTO 9999
GOTO 5000
N4000
IF <CURRENT_POSITION_AXIS_2> <IS_GREATER_THAN_OR_EQUAL_TO> [<STARTING_Y_POSITION> + <DISTANCE_TO_DIGITIZE> - <TOLERANCE>] THEN GOTO 9999
N5000



N2
; 2) Step-over
<X_POS_BEFORE_STEPOVER> = <CURRENT_POSITION_AXIS_1>
<Y_POS_BEFORE_STEPOVER> = <CURRENT_POSITION_AXIS_2>



; Truncate the step over if it will exceed the distance to digitize the segment.
IF <DIRECTION> EQ 0 THEN GOTO 1001
IF <DIRECTION> EQ 1 THEN GOTO 2001
IF <DIRECTION> EQ 2 THEN GOTO 3001
IF <DIRECTION> EQ 3 THEN GOTO 4001
N1001
IF [<CURRENT_POSITION_AXIS_1> - <STEP_ALONG_VALUE>] <IS_LESS_THAN> [<STARTING_X_POSITION> - <DISTANCE_TO_DIGITIZE>] THEN <X_POS_AFTER_STEPOVER> = -1.0*[<CURRENT_POSITION_AXIS_1> - (<STARTING_X_POSITION> - <DISTANCE_TO_DIGITIZE>)] ELSE <X_POS_AFTER_STEPOVER> = -<STEP_ALONG_VALUE>
M115 /X<X_POS_AFTER_STEPOVER> P<TOUCH_PROBE_PLC_INPUT_PARAMETER> F<FAST_PROBE_RATE> L1
GOTO 5001
N2001
IF [<CURRENT_POSITION_AXIS_1> + <STEP_ALONG_VALUE>] <IS_GREATER_THAN> [<STARTING_X_POSITION> + <DISTANCE_TO_DIGITIZE>] THEN <X_POS_AFTER_STEPOVER> = [(<STARTING_X_POSITION> + <DISTANCE_TO_DIGITIZE>) - <CURRENT_POSITION_AXIS_1>] ELSE <X_POS_AFTER_STEPOVER> = <STEP_ALONG_VALUE>
M115 /X<X_POS_AFTER_STEPOVER> P<TOUCH_PROBE_PLC_INPUT_PARAMETER> F<FAST_PROBE_RATE> L1
GOTO 5001
N3001
IF [<CURRENT_POSITION_AXIS_2> - <STEP_ALONG_VALUE>] <IS_LESS_THAN> [<STARTING_Y_POSITION> - <DISTANCE_TO_DIGITIZE>] THEN <Y_POS_AFTER_STEPOVER> = -1.0*[<CURRENT_POSITION_AXIS_2> - (<STARTING_Y_POSITION> - <DISTANCE_TO_DIGITIZE>)] ELSE <Y_POS_AFTER_STEPOVER> = -<STEP_ALONG_VALUE>
M115 /Y<Y_POS_AFTER_STEPOVER> P<TOUCH_PROBE_PLC_INPUT_PARAMETER> F<FAST_PROBE_RATE> L1
GOTO 5001
N4001
IF [<CURRENT_POSITION_AXIS_2> + <STEP_ALONG_VALUE>] <IS_GREATER_THAN> [<STARTING_Y_POSITION> + <DISTANCE_TO_DIGITIZE>] THEN <Y_POS_AFTER_STEPOVER> = [(<STARTING_Y_POSITION> + <DISTANCE_TO_DIGITIZE>) - <CURRENT_POSITION_AXIS_2>] ELSE <Y_POS_AFTER_STEPOVER> = <STEP_ALONG_VALUE>
M115 /Y<Y_POS_AFTER_STEPOVER> P<TOUCH_PROBE_PLC_INPUT_PARAMETER> F<FAST_PROBE_RATE> L1
N5001



; If we didn't trip during step-over, head back to the beginning of this 1) 2) cycle.
IF <LAST_PROBE_TRIP> EQ <PROBE_NOT_TRIPPED> THEN GOTO 1

; If we did trip, go back where we were before the step over, come up in z, then try to step over again
M122
<ABSOLUTE_POSITIONING>
<PROBE_PROTECTION_ENABLED> = <DISABLE_PROBE_PROTECTION>
N222
IF #[<TOUCH_PROBE_PLC_INPUT_PARAMETER>] EQ <PROBE_TRIPPED> THEN GOTO 222
X<X_POS_BEFORE_STEPOVER> Y<Y_POS_BEFORE_STEPOVER>
<PROBE_PROTECTION_ENABLED> = <ENABLE_PROBE_PROTECTION>
G91
IF #[#9011] == 1 THEN M116 /Z P[-#9011] F[#9014]
M126 /Z<PROBE_PULLBACK_DIST> P[#9011] F[#9014]
GOTO 2



; Continue digitizing
GOTO 1

N9999
G<ORIGINAL_POSITIONING_MODE>