;------------------------------------------------------------------------------
; Filename: MPGmacro1.mac
; Description: User Customizable Macro for WMPG Macro Buttons
; Notes:
; Requires: CNC12
; Revision Date: 17 Jun 2024
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
IF #50001                         ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000  ;Skip macro if graphing or searching

; Delete line below and add your logic between N100 and N1000 to customize this macro.
M225 #100 "This is an example macro run from the Macro1 button on the Centroid Wireless MPG\nThe macro is named MPGmacro1.mac and can be found\nin the \cncm\system directory.\nEdit it to include the desired functionality. Press ESC or Cycle Cancel to Exit"

N100                              ;Insert your code between N100 and N1000  



N1000                             ;End of Macro