;------------------------------------------------------------------------------
; Filename: touch_plate_move_p0.cnc
; Description: Generalized Probing Move Command for Touch Plate Macros.
; Notes: Provides both Probed Local (WCS) and Machine Coordinate positions for Axes 1-3.
;        Uses new P0 to stop on any device input.
; Requires: CNC12 V5.20+
; Revision Date: 23 Jan 2025
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Usage: G65 "\cncm\system\touch_plate_move_p0.cnc" x[X Pos] y[Y Pos] z[Z Pos]
; Arguments:  X Pos = X Position to Probe
;             Y Pos = Y Position to Probe
;             Z Pos = Z Position to Probe
;
; Output:
; <TOUCH_PLATE_PROBED_AXIS_1_MACHINE_POSITION>
; <TOUCH_PLATE_PROBED_AXIS_2_MACHINE_POSITION>
; <TOUCH_PLATE_PROBED_AXIS_3_MACHINE_POSITION>
; <TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION>
; <TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION>
; <TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION>
; 
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

;Save Initial Position
<TOUCH_PLATE_MOVE_AXIS_1_INIT_POSITION> = <SV_AXIS_1_WCS_POSITION>
<TOUCH_PLATE_MOVE_AXIS_2_INIT_POSITION> = <SV_AXIS_2_WCS_POSITION>
<TOUCH_PLATE_MOVE_AXIS_3_INIT_POSITION> = <SV_AXIS_3_WCS_POSITION>

;Begin Fast Probing Move
M115 /$<SV_AXIS_1_LABEL>[#x] /$<SV_AXIS_2_LABEL>[#y] /$<SV_AXIS_3_LABEL>[#z] P0 F[<PARAM_TOUCH_PLATE_FAST_PROBE_RATE>]

;Store Probed Point
IF #50001
<TOUCH_PLATE_PROBED_AXIS_1_MACHINE_POSITION> = <SV_AXIS_1_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_MACHINE_POSITION> = <SV_AXIS_2_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_MACHINE_POSITION> = <SV_AXIS_3_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> = <SV_AXIS_1_WCS_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> = <SV_AXIS_2_WCS_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> = <SV_AXIS_3_WCS_POSITION>

;Retract
;Calculate Vector Component Distance
<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_1_INIT_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_2_INIT_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_3_INIT_POSITION>

;Calculate Total Vector Distance
<TOUCH_PLATE_PROBED_VECTOR_DISTANCE> = sqrt[[[<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE>] ^ 2] + [[<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE>] ^ 2] + [[<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE>] ^ 2]]

;Calculate Vector Retract Ratio
  ;We use the ratio later so that the direction of the vector is preserved later in the pull back position calculation.
  ;if we add the parameter directly, an additional check would be needed to see if we have to subtract or add the retract amount based on initial probing direction.
IF <TOUCH_PLATE_PROBED_VECTOR_DISTANCE> != 0 THEN <TOUCH_PLATE_RETRACT_RATIO> = abs[<PARAM_TOUCH_PLATE_RETRACT_DISTANCE>/<TOUCH_PLATE_PROBED_VECTOR_DISTANCE>] ELSE <TOUCH_PLATE_RETRACT_RATIO> = 0

;Calculate Pull Back Distance
  ;If component distance is less than retract distance, go to initial position.
IF abs[<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_1_POSITION> = <TOUCH_PLATE_MOVE_AXIS_1_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_1_POSITION> = <TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]
IF abs[<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_2_POSITION> = <TOUCH_PLATE_MOVE_AXIS_2_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_2_POSITION> = <TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]
IF abs[<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_3_POSITION> = <TOUCH_PLATE_MOVE_AXIS_3_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_3_POSITION> = <TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]

;Begin Retract Move
G65 "#400\system\move_primitive.cnc" x[<TOUCH_PLATE_RETRACT_AXIS_1_POSITION>] y[<TOUCH_PLATE_RETRACT_AXIS_2_POSITION>] z[<TOUCH_PLATE_RETRACT_AXIS_3_POSITION>]

N100 ;Slow Probing Move
;Begin Slow Probing Move
M115 /$<SV_AXIS_1_LABEL>[#x] /$<SV_AXIS_2_LABEL>[#y] /$<SV_AXIS_3_LABEL>[#z] P0 F[<PARAM_TOUCH_PLATE_SLOW_PROBE_RATE>]

;Store Probed Point
IF #50001
<TOUCH_PLATE_PROBED_AXIS_1_MACHINE_POSITION> = <SV_AXIS_1_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_MACHINE_POSITION> = <SV_AXIS_2_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_MACHINE_POSITION> = <SV_AXIS_3_MACHINE_POSITION>
<TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> = <SV_AXIS_1_WCS_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> = <SV_AXIS_2_WCS_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> = <SV_AXIS_3_WCS_POSITION>

;Retract
;Calculate Vector Component Distance
<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_1_INIT_POSITION>
<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_2_INIT_POSITION>
<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE> = <TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> - <TOUCH_PLATE_MOVE_AXIS_3_INIT_POSITION>

;Calculate Total Vector Distance
<TOUCH_PLATE_PROBED_VECTOR_DISTANCE> = sqrt[[[<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE>] ^ 2] + [[<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE>] ^ 2] + [[<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE>] ^ 2]]

;Calculate Vector Retract Ratio
IF <TOUCH_PLATE_PROBED_VECTOR_DISTANCE> != 0 THEN <TOUCH_PLATE_RETRACT_RATIO> = abs[<PARAM_TOUCH_PLATE_RETRACT_DISTANCE>/<TOUCH_PLATE_PROBED_VECTOR_DISTANCE>] ELSE <TOUCH_PLATE_RETRACT_RATIO> = 0

;Calculate Pull Back Distance
;If component distance is less than retract distance, go to initial position.
IF abs[<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_1_POSITION> = <TOUCH_PLATE_MOVE_AXIS_1_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_1_POSITION> = <TOUCH_PLATE_PROBED_AXIS_1_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_1_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]
IF abs[<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_2_POSITION> = <TOUCH_PLATE_MOVE_AXIS_2_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_2_POSITION> = <TOUCH_PLATE_PROBED_AXIS_2_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_2_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]
IF abs[<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE>] < <PARAM_TOUCH_PLATE_RETRACT_DISTANCE> THEN <TOUCH_PLATE_RETRACT_AXIS_3_POSITION> = <TOUCH_PLATE_MOVE_AXIS_3_INIT_POSITION> ELSE <TOUCH_PLATE_RETRACT_AXIS_3_POSITION> = <TOUCH_PLATE_PROBED_AXIS_3_WCS_POSITION> - [<TOUCH_PLATE_PROBED_AXIS_3_DISTANCE> * <TOUCH_PLATE_RETRACT_RATIO>]

;Begin Retract Move
G65 "#400\system\move_primitive.cnc" x[<TOUCH_PLATE_RETRACT_AXIS_1_POSITION>] y[<TOUCH_PLATE_RETRACT_AXIS_2_POSITION>] z[<TOUCH_PLATE_RETRACT_AXIS_3_POSITION>]

N1000                            ;End of Macro